stages:
  - build

variables:
  FRONTEND_PROJECT: "./src"
  NODE_VERSION: "node:18"

.node:base:
  cache:
    paths:
      - $FRONTEND_PROJECT/.npm
    key: ${CI_PROJECT_NAME}_${CI_JOB_NAME}
  before_script:
    - echo ${CI_PROJECT_NAME}_${CI_JOB_NAME}
    - cd $FRONTEND_PROJECT
    - NODE_OPTIONS=\"--max_old_space_size=3512\"
    - node --max-old-space-size=3512

frontend:build:
  image:
    name: $NODE_VERSION
  extends:
    - .node:base
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "src/build/*"
    expire_in: 1h
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - src/**/*
      when: always
