stages:
  - build
  - publish
  - deploy

variables:
  NODE_VERSION: "node:18"
  DEPLOY_SCRIPT_PATH: "docker-compose.yml"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

.node:base:
  cache:
    paths:
      - .npm
    key: ${CI_PROJECT_NAME}_${CI_JOB_NAME}
  before_script:
    - echo ${CI_PROJECT_NAME}_${CI_JOB_NAME}
    - NODE_OPTIONS=\"--max_old_space_size=3512\"
    - node --max-old-space-size=3512

.docker:base:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

frontend:build:
  image:
    name: $NODE_VERSION
  extends:
    - .node:base
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "dist/*"
    expire_in: 1h
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

frontend:publish:
  image: docker:20-dind
  extends:
    - .docker:base
  stage: publish
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:latest
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]

frontend:deploy:
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $CI_REGISTRY_IMAGE:latest"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker compose -f $DEPLOY_SCRIPT_PATH up -d"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker image prune -f"