stages:
  - build
  - publish

variables:
  NODE_VERSION: "node:18"

.node:base:
  cache:
    paths:
      - .npm
    key: ${CI_PROJECT_NAME}_${CI_JOB_NAME}
  before_script:
    - echo ${CI_PROJECT_NAME}_${CI_JOB_NAME}
    - NODE_OPTIONS=\"--max_old_space_size=3512\"
    - node --max-old-space-size=3512

.docker:base:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

frontend:build:
  image:
    name: $NODE_VERSION
  extends:
    - .node:base
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "dist/*"
    expire_in: 1h
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

frontend:publish:
  image: docker:latest
  extends:
    - .docker:base
  stage: publish
  script:
    - docker build -t $CI_REGISTRY_IMAGE:frontend -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:frontend